### ISSUE TITLE
Reset input file 

### ISSUE THREAD

**Issue by alegrm** [danialfarid/angular-file-upload#12] opened 2013-09-20 06:35 UTC
Hi, how I can reset the values of the file? After a successful action done after upload I'd like to clean the form to reuse it. I tried $scope.myform.fileName, but its undefined. Thanks.

**Comment by jasonswett** [comment] 2015-01-09 20:19
Could someone please provide an example of using this? I can't figure out how to do it. Setting my model to `null` seems to have no effect. Setting the element's value to `null` works for me but I don't want to do DOM manipulation in the controller.

**Comment by danialfarid** [comment] 2015-01-10 01:54
@jasonswett this is removed in the latest version 2.1.1. The problem is that some browsers don't let the JavaScript to set the value for input file for security reasons. There are ways to workaround it and I will fix it in the next release.

**Comment by lintaho** [comment] 2015-01-19 23:08
What are some workarounds?

**Comment by danialfarid** [comment] 2015-01-20 00:52
Clone the input file element and replace it. This is just to set it's value to null. It doesn't make sense to set it's value to anything other than null.

**Comment by markvp** [comment] 2015-02-24 01:07
Using the latest version (3.0.7) and the `ng-model` form of access, I am able to set the scope object assigned to ng-model to undefined and it resets the input.

e.g. In HTML template

````
<input type="file" ng-file-upload ng-model="files" />
````

In JS Controller
````
$upload.upload(...).then(cleanup);

function cleanup() {
  scope.files = undefined;
}
````

Essentially, this seems to be fixed in the latest version.

**Comment by danialfarid** [comment] 2015-02-24 02:45
Yes it is fixed in the latest.

**Closed by danialfarid** 2015-02-24 02:45 UTC
Labels: enhancement

**Comment by petecoop** [comment] 2015-03-25 11:28
This appears to be broken in 3.2.4, I reverted to 3.0.7 and it worked again

**Comment by flyawaychen** [comment] 2015-03-25 23:52
I confirm this is broken in the 3.2.4 and 3.0.7 works fine

**Comment by cruel20** [comment] 2015-03-27 10:21
in 3.2.4 
I reset the value of input like: 
```
var x = document.getElementsByClassName("cursor-pointer hidden-input");
var i;
for (i = 0; i < x.length; i++) {
x[i].value = null;
}
```
this clear value of couple of inputs that have the same class name

**Comment by umair-khanzada** [comment] 2015-10-09 14:53
When use multiple="true".
function cleanup() {
  scope.files = undefined;
};
is not working. 
but don't worry i found solution below.

 angular.forEach(
        angular.element("input[type='file']"),
        function(inputElem) {
          angular.element(inputElem).val(null);
        }
      );

**Comment by danialfarid** [comment] 2015-10-09 15:30
@umair-khanzada you shouldn't need to do that, the file input value will be set to null if you set the model value to null and apply scope changes.

**Comment by umair-khanzada** [comment] 2015-10-12 11:00
@danialfarid : i already try $scope.$apply(function(){
$scope.file = null;
}).
 it's working but when i use multiple attribute it's not working.

**Comment by progmars** [comment] 2015-10-12 14:20
I have the same issue. I have a input button to upload multiple files at once (since I intend to support HTML5 browsers anyway):

```                   
 <button type="button" ngf-select ng-model="uploadFiles" name="uploadFiles"
                          ngf-multiple="true"
                          ngf-keep="true"
                          ngf-pattern=".png,.jpg'"
                          ngf-max-size="1MB">Add files</button>
```

Notice: I have `ngf-keep="true"` because I want user to add more files each time he clicks the button. Maybe this is also somehow related to the issue?

Here is what happens:

- user picks files
- I call the following code:
```

                Upload.upload({url: "/upload-path",
                                data: {files: $scope.uploadFiles}})
                // this will be called at the end after all files are uploaded
                .then(function (resp) {
                    // timeout is suggested to break out of ajax callback
                    $timeout(function(){
                             $scope.uploadFiles = null; // clear away file objects, if any
                    });
                }); 
```

I have attached a ng-repeater to $scope.uploadFiles, so I see the list of files. After sending once it is indeed cleared away.

But next time I click "Add files" button, suddenly I get not only the new files but also the old ones. In case if `ngf-keep="true"` is the issue, do I have any options to truly clear away all the files, even the ones kept because of `ngf-keep="true"` ?  I think,, when I call `$scope.uploadFiles`, ng-upload should always completely clear out the selected files, even if `ngf-keep="true"` was specified.

**Comment by progmars** [comment] 2015-10-12 14:29
Oh, it seems that
`vm.uploadFiles = [];`
works but
`vm.uploadFiles = null;`
or
`vm.uploadFiles = undefined;`
does not work.

**Comment by umair-khanzada** [comment] 2015-10-12 17:35
@progmars : i also check $scope.uploadFiles = [No file chosen] it's not work for me.

**Comment by danialfarid** [comment] 2015-10-13 01:53
@umair-khanzada ` $scope.uploadFiles = [No file chosen] ` is different from `$scope.uploadFiles = []`

**Comment by umair-khanzada** [comment] 2015-10-15 06:19
@danialfarid i'll try.

**Comment by azain** [comment] 2015-11-22 08:19
So, what is the final solution to this problem ? I have tried model = [null / false / []/ undefined/ {}] and I still get an error: "a.splice isn't a function! Line: 14762"

**Comment by danialfarid** [comment] 2015-11-22 08:37
There is a separate issue for "a.splice isn't a function! Line:" please post your comment there, this issue is closed.

**Comment by azain** [comment] 2015-11-23 07:09
It's okay, I tried @umair-khanzada 's solution and it's working now. Thanks.

**Comment by singgihmardianto** [comment] 2015-11-23 15:44
Hello, sorry to comment on this issue again. I have a problem with this issue.
I still can't reset the model.
Here is my html:

````
<div class="btn btn-xs btn-default btn-flat ft-modal-upload-btn-select-files" 
   ngf-select ng-model="files"
   ngf-multiple="true" ngf-fix-orientation="false" 
   accept="image/jpg,image/png,image/gif" 
   ngf-keep="'distinct'">
      Or open browser and select 
</div>
<ul class="ft-file-list" ng-if="files != null">
    <span> Files: </span> 
    <li ng-repeat="file in files track by $index"> 
        <div class="ft-modal-upload-filename"> {{ file.name }} </div>
        <a class="text-danger ft-modal-upload-delete-file" ng-click="deleteFile(files, file)"><i class="fa fa-trash"></i></a>
    </li>
</ul>
````

I've tried this

````
Upload.upload()
.then(function (success) {
    $scope.files = [];
    // or
    $scope.files = undefined;
   // or
   $scope.files = null;
   // I've tried using $timeout too but still not work
});
````

Neither worked for me.
Thank you :)

**Comment by danialfarid** [comment] 2015-11-23 17:45
What is not working? What the problem is?

**Comment by singgihmardianto** [comment] 2015-11-24 02:16
@danialfarid after upload success, I deleted the model 
(as I mention I used $scope.files = [] or $scope.files = undefined or $scope.files = null)

But in the HTML

````
<ul class="ft-file-list" ng-if="files != null">
    <span> Files: </span> 
    <li ng-repeat="file in files track by $index"> 
        <div class="ft-modal-upload-filename"> {{ file.name }} </div>
        <a class="text-danger ft-modal-upload-delete-file" ng-click="deleteFile(files, file)"><i class="fa fa-trash"></i></a>
    </li>
</ul>
````

The <li> element still show the old files.

Thank you :)

**Comment by danialfarid** [comment] 2015-11-24 04:42
That doesn't sound right, could you create a jsfiddle? Setting the scope files to empty array should make the ng-repeat on `<li>` to remove them, this is basic angular and has nothing to do with this plugin.

**Comment by singgihmardianto** [comment] 2015-11-26 11:28
Hello @danialfarid sorry for late response. This I've setup the jsfiddle for you.

https://jsfiddle.net/singgihmardianto/8Lyg8hxx/

**Comment by danialfarid** [comment] 2015-11-26 21:25
You are setting a local function parameter to null not a scope variable. Try setting $scope.files to empty array.

**Comment by alzalabany** [comment] 2015-12-09 02:40
same for me 
```
<!-- ng-controller="wallCtrl as wall" -->
<md-button ngf-select ng-model="picFile" name="file"
  ngf-max-size="18MB"
  ngf-resize="{width: 1200, height: 800}" 
  aria-label="description" 
  class="md-accent md-raised" >Add File</md-button>
```

and in controller
```
this.post = function(file,datas,server){
file.upload = Upload.upload({
            url: server + 'feed',
            method: 'POST',
            file: file,
            fields: datas,
            sendFieldsAs: 'form',
            fileFormDataName: 'File'
        }).then(function(response) {
            $timeout(function() {
                self.newPost = {};
            },500);
        },function(){
             ///FAILED
        },function(evt) {
            file.progress = Math.min(100, parseInt(100.0 * evt.loaded / evt.total));
        });
}
`````

as you see i reset `self.newPost = {};` clearing the file upload model which was `              self.newPost.file`

still the file is not cleared.

**Comment by ruizalvaro** [comment] 2016-05-11 20:02
Same issue again. Using $scope.files = [] i can't reset. 11.2.3 Version. I'm not using input type="files" (to clean the DOM).

**Comment by danialfarid** [comment] 2016-05-11 20:53
Create a jsfiddle.

**Comment by singgihmardianto** [comment] 2016-05-12 14:18
@ruizalvaro Do you use any libraries such angular-bootstrap-ui? @danialfarid is right. this is the standard Angular JS works. it should be work. In my experience I use angular-bootstrap-ui and I didn't notice how the plugin works. after spent some time to debug I found that the plugin restrict my model thats why my code didn't work.

**Comment by ruizalvaro** [comment] 2016-05-12 14:32
@singgihmardianto Yes, I am using angular-bootstrap, let me try without this library.

**Comment by jayflo** [comment] 2016-06-21 12:50
I am able to get the form to reset, but after the reset you have to drag the file over twice before the file model is populated again.  Here is a fiddle showing the behavior https://jsfiddle.net/8Lyg8hxx/8/ in v12.0.4

Follow these steps :

1. drag a file onto the box, see the file is populated
2. click the reset button
3. drag a file onto the box again --> file is not populated
4. drag a file onto the box *again* --> now the file is populated

As you can see in the fiddle, I clear the `ng-model` for the file upload element and `form.$setPristine()` the form.  You can also choose to clear the model within the form itself, i.e. `form.file`, but this does not change the behavior.  Is this a bug, or am I doing something incorrectly?

**Comment by resistancecanyon** [comment] 2016-09-19 11:26
@jayflo  +1

**Comment by rajguru827** [comment] 2017-06-14 07:23
In windows safari same file not uploading twice.
`<label class="btn btn-primary btn-sm mb10" 
                        ng-model="files"
                        ngf-select="uploadFiles($file, $invalidFiles)" 
                        ngf-max-size="15MB" 
                        ngf-pattern="'.jpg,.png,.jpeg,.pdf,.doc,.docx,.XLS,.XLSX'"
                        ngf-accept="'.jpg,.png,.jpeg,.pdf,.doc,.docx,.XLS,.XLSX'"
                        accept=".jpg,.png,.jpeg,.pdf,.doc,.docx,.XLS,.XLSX" >
                        Upload File
                    </label>`
` $scope.uploadFiles = function (file, errFiles) {         
            $scope.f = file;
            $scope.errFile = errFiles && errFiles[0];
            if ($scope.errFile) {
                if ($scope.errFile.$error == "maxSize") {
                    growl.error('File size is more than ' + 15 + ' Mb', { title: 'Invalid file size', disableCountDown: true });
                } else if ($scope.errFile.$error == "pattern") {
                    growl.error('Only .jpg,.png,.jpeg,.pdf,.doc,.docx,.XLS,.XLSX are accepted', { title: 'Invalid file type', disableCountDown: true });
                }                
            }
            if (file) {
                $scope.file = {};
                $scope.file.UploadedImage = file;
                $scope.file.name = file.name;
                $scope.file.type = 1;
                file.upload = Upload.upload({
                    url: '../serverHandlers/fileHandler.ashx',
                    data: $scope.file
                });
                file.upload.then(function (response) {
                    
                    $scope.files = undefined;
                    $timeout(function () {                        
                        file.result = response.data;
                        var FileRoot = file.result.filepath.split(':')[0];
                        var FilePath = file.result.filepath.split(':')[1];
                        $scope.UserFileName = FilePath;
                        if (file.result.filepath == 'NoFiles') {
                            growl.error("Please Select Files", { title: 'Error!', disableCountDown: true });
                        } else if (file.result.filepath == "InvalidSession") {
                            $scope.isnavigate = true;
                            $state.go('user.signout')
                        } else if (file.result.filepath == "Exception") {
                            growl.error("Error While Uploading File Please try again", { title: 'Error!', disableCountDown: true });
                        } else {
                            $scope.objPreviewRequest = {
                                FilePath: FilePath,
                                PreviousPath: "preview",
                                IsTemplateMergePreview: false
                            };
                            $scope.templatePreviewGet($scope.objPreviewRequest)
                            $scope.IsTemplateupload = true;
                        }

                        $scope.excel.models = {};
                        $scope.excel.models.file = [];
                    });
                }, function (response) {
                    if (response.status > 0)
                        $scope.errorMsg = response.status + ': ' + response.data;
                    growl.error($scope.errorMsg, { title: 'Error', disableCountDown: true });
                });
            }
        }`
