### ISSUE TITLE
Drag n' Drop Changed?! directive ng-file-select to ng-file-changed

### ISSUE THREAD

**Issue by nullpunkt** [danialfarid/angular-file-upload#500] opened 2015-01-12 09:35 UTC
I used to trigger the file upload (in previous versions) via directive ng-file-select. Now i switched to head version of angular-file-upload and angular 1.3.8. and my fileupload doesn't work any more.
I figured out that when selecting a file or using drag n drop the function behin the ng-file-changed html attribute is used instead of ng-file-select in previous versions. Hopefully this saves some time of others.

After removing ng-files-select from the html tag the event isn't triggered anymore. So it seems like the js event is bind only if ng-file-select is used BUT ng-file-change fn is used for progressing the event.

**Comment by danialfarid** [comment] 2015-01-12 11:26
ng-file-select should work too. If a value is provided it would set it at ng-file-change for backward compatibility.

**Comment by nullpunkt** [comment] 2015-01-13 07:08
I could reproduce this behaviour in http://jsfiddle.net/zc51x4g3/ - The function behind ng-file-change is only called if both - ng-file-change AND ng-file-select are defined.

**Comment by raaad** [comment] 2015-01-21 08:47
I think the problem is in line 229 (angular-file-upload.js v2.1.1):
```javascript
 attr.ngFileChange = attr.ngFileSelect;
```
It could be fixed with this:
```javascript
 changeFn = $parse(attr.ngFileSelect);
```

**Comment by danialfarid** [comment] 2015-01-21 16:36
Line 228 need to  be moved to line 197.
Will fix it in the next release. This was working at version 2.0.x and is broken for versions 2.1.0 and 2.1.1

**Closed** 2015-01-24 17:02 UTC
